### ISSUE TITLE
[FEATURE] Built-in Mx1A1 inference engine via MMDeploy

### ISSUE THREAD

**Issue by frontierkodiak** [frontierkodiak/polliOS-core#26]
**Is your feature request related to a platform? Please describe.**
- All platforms.

**Describe the solution you'd like**
Allow users to run detection on-device (new default). 

**Describe alternatives you've considered**
- We could force users to deploy Mx1A1 with TorchServe, but this could be a significant barrier.

**Additional context**

**To-Do:**
- [ ] Export quantized mmdeploy Mx1A1
- [ ] Build ProviderSingleton to load model and build task processor.
- [ ] Integrate ProviderSingleton with Module schema (add new endpoint type & relevant params).
- [ ] Build Module.invoke_provider() method. Document invoke_xxx() API.
- [ ] Update Brain config schema.
- [ ] Verify Brain config -> Module -> ProviderSingleton flow.

**Needed for production:**
_Related but may fall in the domain of another issue._

- [ ] AssetManager to detect platform, pull appropriate models/assets, and persist them locally.
- [ ] polliOS-core setup.py must install the dependencies for the desired inference engine (onxx, onxx-gpu, tensorrt, ncnn, open-vino, etc)
