### ISSUE TITLE
[FEATURE] PolliDB: Support SQLite backend

### ISSUE THREAD

**Issue by frontierkodiak** [frontierkodiak/polliOS-core#29]
**Is your feature request related to a problem? Please describe.**
SQLite will be the default PolliDB backend. Should be sufficient for casual users with max records measured in the hundreds of thousands.

**Is your feature request related to a platform? Please describe.**
All platforms. SQLite will be the new default PolliDB backend. 

**Describe the solution you'd like**
polliOS-core should initialize a polliDB.db database file upon first use. polliDB.db should default to ./data, but user should be able to specify a path in the backend config, or as an environment variable.

We should provide a migration script (accessible thru UI) migrate_sqlite_polliDB_to_MySQL.py that will perform migration from one backend to the other, provided connection parameters.

**Describe alternatives you've considered**
Rely on dockerized/cloud MySQL server

**Additional context**
Users should be able to easily migrate from SQLite to a MySQL backend (if they outgrow SQLite, or opt for hosted Polli+/Polli Pro).

**To-Do:**

- [ ] Update BackendSingleton to allow sqlite backend. 
- [ ] Refactor backend setup code to allow polliDB sqlite, choose sqlite as default if another polliDB backend is not specified.
- [ ] Save polliDB.db in (default) ./data/, or allow users to pass path in backend config or env var.
