### ISSUE TITLE
[FEATURE] Built-in lightweight Mx1A2 inference engine via MMDeploy

### ISSUE THREAD

**Issue by frontierkodiak** [frontierkodiak/polliOS-core#30]
**Is your feature request related to a problem? Please describe.**
We would like users to be able to run Mx1A2 (classification) models on-device without needing on a separate Brain torchserve Docker container.

**Is your feature request related to a platform? Please describe.**
All platforms 

**Describe the solution you'd like**
Full SOTA Mx1A2 MultiTask models are difficult to deploy via MMDeploy and likely consume too many system resources for most users. We can develop simplified, single-task classifiers instead that can be integrated into ProviderSingleton. 

Full-strength models could be run via an external TorchServe container, or I may provide hosted inference endpoints as a part of Polli+/Polli Pro.

**Describe alternatives you've considered**

**Additional context**

**To-Do:**
- [ ] Write convert_multitask_dataset_to_mmlab2.py
- [ ] Train lightweight models:
- [ ] angio
- [ ] aves
- [ ] reptilia
- [ ] mammalia
- [ ] arthropoda
- [ ] Quantize & dump metainfo for mmdeploy SDK
- [ ] Upload model assets to PolliServe (inc. taxonID_mapping)
