### ISSUE TITLE
[PLATFORM] Inference engine on macOS

### ISSUE THREAD

**Issue by frontierkodiak** [frontierkodiak/polliOS-core#31]
Develop and test lightweight CoreML Brain modules. Integrate into ProviderSingleton.

**Platform**:
ARM-based macOS platforms.

**Limitations**:

**To-do**:
Deploy Mx1A2-lite models:
- [ ] aves
- [ ] angio
- [ ] reptilia
- [ ] arthro
Deploy Mx1A1 model:
_Note that we must compile TorchScript for ARM to run conversion on detection models. See [docs](https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/macos-arm64.md)._
- [ ] Compile macOS mmdeploy with coremltools, TorchScript.
- [ ] Deploy Mx1A1

- [ ] Integrate into ProviderSingleton.
- [ ] Test inference
- [ ] Upload CoreML bundles into PolliServe
- [ ] Integrate platform detection, asset grabbing into polliOS AssetManager
